# Generated by Django 5.1.6 on 2025-03-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AllProductsModel",
            fields=[
                ("pd_id", models.AutoField(primary_key=True, serialize=False)),
                ("pd_name", models.CharField(max_length=30)),
                ("pd_model", models.CharField(max_length=30)),
                ("pd_brand", models.CharField(max_length=30)),
                ("pd_description", models.TextField()),
                ("pd_pricing", models.IntegerField()),
            ],
        ),
    ]
