# Generated by Django 5.1.6 on 2025-03-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="allproductsmodel",
            name="pd_image",
            field=models.ImageField(null=True, upload_to="product_images/"),
        ),
    ]
