# Generated by Django 5.1.6 on 2025-03-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_products", "0002_allproductsmodel_pd_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allproductsmodel",
            name="pd_description",
            field=models.TextField(null=True),
        ),
    ]
