# Generated by Django 5.1.6 on 2025-03-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_products", "0003_alter_allproductsmodel_pd_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="allproductsmodel",
            old_name="pd_image",
            new_name="product_images",
        ),
        migrations.AlterField(
            model_name="allproductsmodel",
            name="pd_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
