# Generated by Django 5.1.6 on 2025-03-06 11:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "app_products",
            "0004_rename_pd_image_allproductsmodel_product_images_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="allproductsmodel",
            old_name="product_images",
            new_name="pd_images",
        ),
    ]
